jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"
      - uses: julia-actions/cache@v2
      - uses: julia-actions/add-julia-registry@v2
        with:
          registry: ITensor/ITensorRegistry
          ssh-key: ${{ secrets.DOCUMENTER_KEY }}
      - uses: julia-actions/julia-runtest@v1
