name: "CompatHelper"

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write

jobs:
  CompatHelper:
    name: "CompatHelper"
    uses: "ITensor/ITensorActions/.github/workflows/CompatHelper.yml@main"
    with:
      local-registry-names: "ITensorRegistry"
      local-registry-urls: "https://github.com/ITensor/ITensorRegistry.git"
